using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using CustomerSupportAgent.Core.Models;
using CustomerSupportAgent.Core.Orchestrator;
using CustomerSupportAgent.Infrastructure.Data;

namespace CustomerSupportAgent.Api.Controllers;

[ApiController]
[Route("api/[controller]")]
public class ApprovalController : ControllerBase
{
    private readonly AppDbContext _dbContext;
    private readonly IServiceScopeFactory _scopeFactory;

    public ApprovalController(AppDbContext dbContext, IServiceScopeFactory scopeFactory)
    {
        _dbContext = dbContext;
        _scopeFactory = scopeFactory;
    }

    [HttpPost("{ticketId}/approve")]
    public async Task<IActionResult> ApproveDraft(Guid ticketId, [FromBody] ApproveRequest request)
    {
        var ticket = await _dbContext.Tickets
            .Include(t => t.Drafts)
            .FirstOrDefaultAsync(t => t.Id == ticketId);

        if (ticket == null)
        {
            return NotFound($"Ticket {ticketId} not found.");
        }

        var latestDraft = ticket.Drafts.OrderByDescending(d => d.CreatedAt).FirstOrDefault();
        if (latestDraft == null)
        {
            return BadRequest("No draft found to approve.");
        }

        if (!string.IsNullOrWhiteSpace(request.EditedContent))
        {
            latestDraft.Content = request.EditedContent.Trim();
        }

        latestDraft.Status = DraftStatus.Approved;
        latestDraft.ActionedAt = DateTime.UtcNow;
        latestDraft.OperatorComments = "Approved by operator.";

        ticket.Status = TicketStatus.Sending;
        ticket.UpdatedAt = DateTime.UtcNow;
        await _dbContext.SaveChangesAsync();

        await Task.Delay(1000);

        ticket.Status = TicketStatus.Sent;
        ticket.UpdatedAt = DateTime.UtcNow;

        var emailDispatchLog = new AgentLog
        {
            TicketId = ticket.Id,
            AgentName = "System",
            Action = "Dispatched Email",
            Input = $"Recipient: {ticket.CustomerEmail}",
            Output = $"Email dispatched successfully.\n\nSubject: Re: {ticket.Subject}\nBody:\n{latestDraft.Content}",
            Status = "Success",
            CreatedAt = DateTime.UtcNow
        };
        _dbContext.AgentLogs.Add(emailDispatchLog);
        await _dbContext.SaveChangesAsync();

        return Ok(new { message = "Email approved and successfully sent.", ticket });
    }

    [HttpPost("{ticketId}/reject")]
    public async Task<IActionResult> RejectDraft(Guid ticketId, [FromBody] RejectRequest request)
    {
        if (string.IsNullOrWhiteSpace(request.Comments))
        {
            return BadRequest("Comments explaining the reason for rejection are required.");
        }

        var ticket = await _dbContext.Tickets
            .Include(t => t.Drafts)
            .FirstOrDefaultAsync(t => t.Id == ticketId);

        if (ticket == null)
        {
            return NotFound($"Ticket {ticketId} not found.");
        }

        var latestDraft = ticket.Drafts.OrderByDescending(d => d.CreatedAt).FirstOrDefault();
        if (latestDraft == null)
        {
            return BadRequest("No draft found to reject.");
        }

        latestDraft.Status = DraftStatus.Rejected;
        latestDraft.ActionedAt = DateTime.UtcNow;
        latestDraft.OperatorComments = request.Comments.Trim();

        ticket.Status = TicketStatus.Rejected;
        ticket.UpdatedAt = DateTime.UtcNow;
        await _dbContext.SaveChangesAsync();

        // Create a new DI scope for the background task to avoid disposed DbContext exceptions
        _ = Task.Run(async () =>
        {
            using (var scope = _scopeFactory.CreateScope())
            {
                try
                {
                    var orchestrator = (WorkflowOrchestrator)scope.ServiceProvider.GetService(typeof(WorkflowOrchestrator))!;
                    await orchestrator.ProcessTicketAsync(ticket.Id);
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Error running background orchestrator loop for ticket rejection {ticket.Id}: {ex.Message}");
                }
            }
        });

        return Ok(new { message = "Draft rejected. A new version is being generated by the support agents in the background.", ticket });
    }
}

public record ApproveRequest(string? EditedContent);
public record RejectRequest(string Comments);
